### ISSUE TITLE
Can't get subtasks/grouping working

### ISSUE THREAD

**Issue by luxmedia** [firstandthird/load-grunt-config#107]
Hello,

How can i handle subtasks with load-grunt-config?
Before switching i had in my `Grunfile.js` something like this:

Clean-Task config:

```
        // clean dist directory from old files
        clean: {
            build: {
                src: [ '<%= globalConfig.dest %>' ]
            },
            stylesheets: {
                src: [ '<%= globalConfig.css_dist_folder %>/**/*.css', '!<%= globalConfig.css_dist_file %>', '!<%= globalConfig.css_dist_file_min %>' ]
            },
            scripts: {
                src: [ '<%= globalConfig.js_dist_folder %>/**/*.js', '<%= globalConfig.do_not_clean_js %>' ]
            },
        },
```

Clean-Task registration:

```
    grunt.registerTask(
        'build',
        'Compiles all of the assets and copies the files to the distribution directory.',
        [ 'clean:build', 'copy', 'stylesheets', 'scripts', 'cleanempty' ]
    );
```

and the `stylesheets` and `scripts` tasks invoke `clean:stylesheets` and `clean:scripts`.

But how can i transfer this subtask-invokation to the load-grunt-config structure?
I tried task-grouping, but couldn't get it working.

For example my `aliases.yaml` contains:

```
build:
  description: 'Compiles all of the assets and copies the files to the distribution directory.'
  tasks:
    - clean__build
    - copy
    - stylesheets
    - scripts
    - cleanempty
```

and in `grunt/clean-tasks.yaml` i have:

```
# clean dist directory from old files
clean__build:
  src:
    - '<%= globalConfig.dest %>'

clean__stylesheets:
  src:
    - '<%= globalConfig.css_dist_folder %>/**/*.css'
    - '!<%= globalConfig.css_dist_file %>'
    - '!<%= globalConfig.css_dist_file_min %>'

clean__scripts:
  src:
    - '<%= globalConfig.js_dist_folder %>/**/*.js'
    - '<%= globalConfig.do_not_clean_js %>'
```

According to the documentation here. But on building i get the error:

```
Running "build" task
Warning: Task "clean__build" not found.
```

Any ideas what i am doing wrong?

Regards,
Volker
