### ISSUE TITLE
How to use grunt-newer with grunt-config?

### ISSUE THREAD

**Issue by luxmedia** [firstandthird/load-grunt-config#108]
Hello, how can i use the `grunt-newer` plugin within `load-grunt-config`?

If i follow the instructions i should prefix the tasks (i suppose in my `aliases.yaml`) with `newer:`. What i get is the following error:

```
Running "newer:scripts" (newer) task
Fatal error: The "newer" prefix is not supported for aliases
```

I think its not as easy as i thought to implement -newer within grunt-config, isn't it?

A second question: Whats about loading tasks/plugins without the `grunt-` namespace? I tried the wildcard `*` instead of `grunt-*` in the grunt-config but without success. "The task could not be found ..."

Regards
Volker

**Comment by apla** [comment]
same problem. fixed using aliases file

**Comment by kyvour** [comment]
+1

**Comment by SolomoN-ua** [comment]
Hi guys, can someone provide an example of configuration, for testing purpose?

**Comment by kyvour** [comment]
newer works OK for me. There is my aliases.yml file:

``` yaml
css:
  description: |
    Task for development.
    The task performs minification for images, compilation of scss files in
    development mode and process styles with postcss plugins.
    You can use this task when you need only rebuild your css.
    To run this task you should use 'grunt css' command.
  tasks:
    - newer:imagemin
    - sass:dev
    - newer:postcss:css

js:
  description: |
    Task for development.
    The task checks javascript files for coding standards and makes some their
    beautification.
  tasks:
    - newer:jshint
    - newer:uglify:beauty

dev:
  description: |
    Task for development.
    The main task for process theme in a development mode.
    This task processes all subtasks for this theme: performs minification for
    images, checks javascript files files for coding standards and makes their
    beautification, compiles scss files in development mode and processes styles
    with postcss plugins.
  tasks:
    - newer:imagemin
    - newer:jshint
    - newer:uglify:beauty
    - sass:dev
    - newer:postcss:css
```
