### ISSUE TITLE
Splitting JavaScript files out doesn't seem to work if the configPath is something other than grunt.

### ISSUE THREAD

**Issue by curtisblackwell** [firstandthird/load-grunt-config#138]
When I use a folder called `tasks`, I'm unable to load JavaScript files.

```js
module.exports = function(grunt) {
  require('load-grunt-config')(grunt, {
    configPath: 'tasks'
  });
};
```

However, if I stick to the default of `grunt` it works fine.

```js
module.exports = function(grunt) {
  require('load-grunt-config')(grunt);
};
```

I'm unable to stick to `grunt`, though, because I'm using this as part of a larger project where that would make a mess of the filesystem. The actual `configPath` pulls from a couple folders nested deeper than just `tasks`.

Here's the error I get:

```
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'tasks/prompt.js'
Warning: Task "prompt:init" not found. Use --force to continue.

Aborted due to warnings.
```

---

In case it's helpful, here are the other files I'm working with.

`package.json`:  
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "author": "",
  "dependencies": {
    "grunt": "0.4.5",
    "grunt-prompt": "1.3.0",
    "load-grunt-config": "0.19.0"
  }
}
```

`tasks/prompt.js`:  
```js
module.exports = {
  init: {
    options: {
      questions: [
        {
          config: 'shell.test.command',
          type: 'input',
          message: 'What command do you wanna run?',
          default: 'echo its working!'
        },
        {
          config: 'shell.npm_install.command',
          type: 'checkbox',
          message: 'Which tasks do you want to use?',
          choices: [
            {
              name: 'Autoprefixer',
              value: 'autoprefixer grunt-postcss'
            },
            {
              name: 'BrowserSync',
              value: 'grunt-browser-sync',
              checked: true
            }
          ],
          filter: function(value) {
            return 'npm install ' + value.join(' ') + ' -SE';
          }
        }
      ],
      then: function(results, done) {
        grunt.file.write('test.json', JSON.stringify(results));
      }
    }
  }
}
```

**Comment by SolomoN-ua** [comment]
Hi @curtisblackwell, try this:
```js
require('load-grunt-config')(grunt, {
    configPath: path.join(process.cwd(), 'tasks')
});
```
just checked it works!

**Comment by curtisblackwell** [comment]
Hey @SolomoN-ua,

Thanks! That _did_ load the JavaScript file, **but** it's not reading my `config`.

```js
var settings = grunt.file.readYAML('settings.yaml');

require('load-grunt-config')(grunt, {
  configPath: path.join(process.cwd(), 'tasks'),
  overridePath: 'custom',
  config: {
    s: settings
  }
});
```

In all of my YAML files, I'm able to use `'<%= s.some_setting %>`, but with the JavaScript, I get this error:

> Fatal error: s is not defined

Is there anything special I need to do to get `s` into the JavaScript file?

**Comment by SolomoN-ua** [comment]
Can you provide example of your js config file?

**Comment by SolomoN-ua** [comment]
@curtisblackwell I mean expample with `'<%= s.some_setting %>'`

**Comment by curtisblackwell** [comment]
Okay, so here's a stripped down version of what I'm working with:

`core/tasks/aliases.yaml`  

```yaml
init:
  tasks:
    - prompt:init
    - shell:npm_install
```

`core/tasks/prompt.js`  

```js
module.exports = {
  init: {
    options: {
      questions: [
        {
          config: 'prompt.pkgs.sass',
          type: 'confirm',
          message: 'Do you use 🐍 Sass?',
          default: true
        },
        {
          config: 'prompt.pkgs.autoprefixer',
          type: 'confirm',
          message: 'How about Autoprefixer?',
          default: true
        },
        {
          config: 'prompt.pkgs.watch',
          type: 'confirm',
          message: 'Browsersync? (live reload, synced actions across devices, etc.)',
          default: true
        },
        {
          config: 'prompt.pkgs.usemin',
          type: 'confirm',
          message: 'Concat, minify, and uglify before serving code? (grunt-usemin)',
          default: true
        }
      ],


      then: function(results, done) {
        var installList = s.pkgs.default.join(' ') + ' ';
        for (var group in grunt.config('prompt.pkgs')) {
          // Append packages to the install list if the dev chose this group.
          installList += grunt.config('prompt.pkgs')[group] ? s.pkgs[group].join(' ') + ' ' : '';
        }

        grunt.config.set('shell.npm_install.command', 'npm install ' + installList + ' -SE');
      }
    }
  }
}
```

`core/tasks/shell.yaml`  

```yaml
npm_install:
  command: 'echo There seems to have been an error.'

test_override:
  command: echo '<%= s.shell.test_override_text %>'
```

`core/packages.yaml`  

```yaml
preinstalled:
  - grunt@0.4.5
  - grunt-prompt@1.3.0
  - grunt-shell@1.1.2
  - load-grunt-config@0.19.0
  - path@0.12.7
default:
  - grunt-contrib-clean@0.6.0
  - grunt-contrib-copy@0.8.2
  - js-yaml@3.4.3
sass:
  - grunt-contrib-sass@0.9.2
autoprefixer:
  - autoprefixer@6.1.0
  - grunt-postcss@0.7.1
watch:
  - grunt-browser-sync@2.1.3
  - grunt-contrib-watch@0.6.1
usemin:
  - grunt-contrib-concat@0.5.1
  - grunt-contrib-cssmin@0.14.0
  - grunt-contrib-uglify@0.10.0
  - grunt-usemin@3.1.1
```

`custom/shell.yaml`  

```yaml
test_override:
  command: echo OVERRIDING core/tasks/shell.yaml
```

`Gruntfile.js`  

```js
module.exports = function(grunt) {
  var path      = require('path');
  var settings  = grunt.file.readYAML('settings.yaml');
  settings.pkgs = grunt.file.readYAML('core/packages.yaml');

  require('load-grunt-config')(grunt, {
    configPath: path.join(process.cwd(), 'core/tasks'),
    overridePath: 'custom',
    config: {
      s: settings
    }
  });
}
```

`package.json`  

```json
{
  "name": "test",
  "description": "test",
  "version": "0.0.1",
  "license": "CC-BY-SA-4.0",
  "dependencies": {
    "grunt": "0.4.5",
    "grunt-prompt": "1.3.0",
    "grunt-shell": "1.1.2",
    "load-grunt-config": "0.19.0",
    "path": "0.12.7"
  }
}
```

`settings.yaml`  

```yaml
shell:
  test_override_text: Uh-oh! I do not work.
```
