### ISSUE TITLE
register-task.yaml

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/load-grunt-config#5]
Be able to define tasks in a register-task.yaml (or maybe aliases.yaml).

``` yaml
default:
  - jshint
  - concat
prod:
  - uglify
dev:
  - default
  - connect
  - watch
```

@williamsb @cbas @dylang @belelros @dawnerd  Do you guys have any thoughts on this?  Would you use it?
