### ISSUE TITLE
Object #<Object> has no method 'replace' error for tasks with a description

### ISSUE THREAD

**Issue by ghost** [firstandthird/load-grunt-config#70]
With 0.10.0 and the new option to add descriptions to tasks in the aliases.yaml file, I'm unable to run tasks for which I've added a description. With the following code in aliases.yaml:

```
build:
  description: 'Build static website for deployment'
  tasks:
    - 'clean:temp'
    - 'clean:dist'
    - 'check_src'
    - 'format_src'
    - 'build_dist'
    - 'usemin_dist'
    - 'process_dist'
    - 'clean:temp'
```

I get the error: `Warning: Object #<Object> has no method 'replace' Use --force to continue.`

`Grunt --help` gives the following description for the `build` alias: `build  Alias for "[object Object]" task.`

Other tasks (to which I haven't added a description), run just fine. The full syntax of my aliases.yaml before adding the description to the build task is [here](https://github.com/beuys/beuys/blob/develop/.grunt/aliases.yaml).
